export const SET_BOARD_STATE = "SET_BOARD_STATE";
export const SET_BOARD_DIMENSIONS = "SET_BOARD_DIMENSIONS";
export const UPDATE_BOARD_STATE = "UPDATE_BOARD_STATE";

export const SET_NODE_CLICK_ACTION = "SET_NODE_CLICK_ACTION";
export const SET_TILE_CLICK_ACTION = "SET_TILE_CLICK_ACTION";
export const SET_EDGE_CLICK_ACTION = "SET_EDGE_CLICK_ACTION";
