export const SET_BOARD_STATE = "SET_BOARD_STATE";
export const SET_BOARD_DIMENSIONS = "SET_BOARD_DIMENSIONS";
export const UPDATE_BOARD_STATE = "UPDATE_BOARD_STATE";

export const SET_NODE_CLICK_ACTION = "SET_NODE_CLICK_ACTION";
export const SET_TILE_CLICK_ACTION = "SET_TILE_CLICK_ACTION";
export const SET_EDGE_CLICK_ACTION = "SET_EDGE_CLICK_ACTION";

export const SET_ROLL = "SET_ROLL";
export const SET_ROLLING = "SET_ROLLING";

export const START_GAME = "START_GAME";

export const PLACE_SETTLEMENT = "PLACE_SETTLEMENT";
export const PLACE_CITY = "PLACE_CITY";

export const ADD_PLAYER = "ADD_PLAYER";
